### ISSUE TITLE
error variable not defined / used outside intended scope

### ISSUE THREAD

**Issue by 1N50MN14** [DoctorEvidence/lmdb-store#1]
Hi @kriszyp 

First of all thank you *so* much for making lmdb-store available, so well thought of, and so much needed.

Apologies if I'm missing on something here, I believe [#L383]( https://github.com/DoctorEvidence/lmdb-store/blob/master/index.js#L383) will break as `error` is not defined within the timeout callback scope, should've been a try catch statement around `writeBatch()` instead?

One other question if I may, have you experienced any partial corruptions in production due to resizing and if so would it be a good idea to make it optional (I can submit a PR)?

**Comment by kriszyp** [comment]
> I believe #L383 will break as error is not defined within the timeout callback scope
Good catch, thank you, I'll fix that.

> One other question if I may, have you experienced any partial corruptions in production due to resizing and if so would it be a good idea to make it optional (I can submit a PR)?

We have been running this in production and multiple test servers for about a year, with dozens of different databases and multiple processes connecting to the same databases (which trigger cross-process resizing) and with many thousands of resizes occurring, and I have never seen a single instance of database corruption due to resizing. However, if you want to avoid resizing, you should be able to avoid it by simply setting setting a higher initial `mapSize` property in the `options` to creating an LMDB store. If the mapSize is bigger than you will ever use, it shouldn't ever resize (and if you do run out of space, you probably would prefer resizing to crashing, I would think).

(FWIW, I _have_ seen database corruption due to a server crashing when we had `noSync` enabled, which is part of the motivation for this package and why it is essential to leave that option off and use proper syncing).

**Comment by 1N50MN14** [comment]
oh thank you I completely missed `mapSize` was an option I can pass. I'm actually shooting to horizontally scale lmdb-store by keeping track of the ranges on each node (first, last, ordered timestamp uuids), a simple kubernetes operator I've written to track the nodes/attach-reattach volumes, and a cpu/memory bound HPA to scale the instances (one pod per node). 

By the way, this is also made possible thanks to `ordered-binary` and `dpack`. The one thing I need to check is volume resizing and see what happens.. I assume you're clustering lmdb-store based on the number of cpus on each machine if I may ask (one writer, cpus-1 readers)? I tried worker threads, that made node-lmdb panic.

Also thank you for sharing your experience using lmdb-store in production, this is really good to hear! noSync disabled too. I've spent countless days trying to find anything out there, that simply does transactions+range+streaming, without the added bloat, until I came across lmdb -> node-lmdb -> lmdb-store. So well thought off, so straight forward, it was such a life saver the only thing I could think of was "thank you thank you thank you".

PS: I did manage to hit the error, I ran consecutive writes (async) on the same key, then the error showed up:
```
ReferenceError: error is not defined
    at Timeout.setTimeout.runNextBatch (/dev/dfv/platform/db/node_modules/lmdb-store/index.js:383:15)
```

**Comment by kriszyp** [comment]
We run 4 processes on our server (no clustering across machines though). There are more cores than that on the machine, but plenty of other services running, so most of the cores don't get bored. We actually allow writes from any of the processes, and use the conditional write feature to ensure atomicity/consistency. Your sharding/delegation approach sounds like a good plan to me. Glad to hear you are using some of our other packages too!

Anyway, pushed a fix that error reference. BTW, were you directly calling `scheduleCommit()`? I am curious how it would end up with no `scheduledOperations` (I never seen it with our put calls, even using the repeated/same key, but I never call `scheduleCommit()` directly).

**Comment by 1N50MN14** [comment]
That was quick, thank you! The error is somehow is gone as well, strangely enough, as my calls shouldn't have triggered it all together - I wasn't using `scheduleCommit()`. 

Here's the code snippet for my "insert" operation:
```javascript
async insert(entity, options)
{
  const {key, data} = entity,
        {silent} = (options || {}),
        {store, hashKeyBuffer} = this._resolveKeyPath(key),
        input = this._validateData(data);

  const success = await store.put(hashKeyBuffer, serialize(input), null);

  if(!success && !!silent == false)
    throw new LMDBError(409, 'CONFLICT', `Key ${key} exists`);

  return success;
}
```
`_resolveKeyPath` simply returns the correct store and `toBufferKey(key)` whereas `_validateData()` makes sure input is a valid/non-corrupt JSON, `serialize()` is dpack's.

My `update` method is pretty much identical, excepting for my put call which looks like so:
```javascript
 //ifValue is serialized if present
 const success = await store.put(hashKeyBuffer, serialize(input), ifValue);
``` 

From there I simply ran:
```javascript
(async () =>
  const entity = { key: `event/${tuid}`, data:{foo:1} };
  await insert(entity)
  await update({ key:entity.key, data:{bar:2} });
  await update({ key:entity.key, data:{bar:2} });
})()
```
The error is somehow gone now, data is correctly stored...

Very interesting you allow for writes from any of the processes, I guess an "insert" operation would be a `put(key, value, null)` as I'm doing right now, but when it comes to updating a key do you first fetch it and pass it as `put()`'s `ifValue`?  

`remove` might be problematic, thinking out loud , if it's immediately followed by `put` within the same async batch, but this could potentially be solved by nulling the value instead of removing the key...

**Comment by kriszyp** [comment]
This looks good. It is worth noting that if you are doing an `await` for each individual `update`/`put`, they will each end up in a different transaction (because they are each awaiting the completion of the last transaction before the returned promise resolves). However, if you do a Promise.all of the put results they will go in the same transaction (faster and more atomic). Or you can even take advantage of the fact that they are all committed in order and just await the last update:
```
  insert(entity)
  update({ key:entity.key, data:{bar:2} });
  await update({ key:entity.key, data:{bar:2} }); // only need to await if you want to wait for the async transaction of all these updates to finish
```
> when it comes to updating a key do you first fetch it and pass it as put()'s ifValue?

That's correct, that's exactly what we do. Most of our use of LMDB is for caching data and transformed data from various sources (MSSQL, postgres, and AI backend code tasks and storage). So each entity is usually either stored as an "invalidated" entry (waiting to be accessed and recomputed), or a cached entry, but either way, we either get, or have a cached copy of the existing entry value that we use to validate the assumed state of the db to maintain consistency.

**Comment by 1N50MN14** [comment]
> Or you can even take advantage of the fact that they are all committed in order and just await the last update

Ahhh!! the light bulb finally went off in my head! Since we are relying on `ifValue` then we might just as well batch the operations we need! atomic + async + multiple process writes  + complete control over failing the whole batch before even attempting to write + additional safety through `ifValue` - all at the cost of a single cheap `get` per write!!!

I'm gonna scrap that silly function of mine! Batch everything instead, the last batch operation will be awaited for anyway, the logic will work on single write operations too!

Ingenious!! Thank for the advice and for politely nudging me in the right direction!!

**Comment by 1N50MN14** [comment]
@kriszyp Closing since the original issue is long resolved, many thanks again!
