### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kylebernhardy** [DoctorEvidence/lmdb-store#22]
Hi, I am picking up my questions from node-lmdb https://github.com/Venemo/node-lmdb/issues/182.

There are a lot of features in lmdb-store that would be very helpful to our product but we use dupsorted keys for our indices. Can dupsorted keys be implemented in this project or can I use the underlying node-lmdb library to work with them?

**Comment by kriszyp** [comment]
Yes, working on it (or you can use the underlying node-lmdb API, although hopefully this approach will work nicely):
https://github.com/DoctorEvidence/lmdb-store/commit/8ed5d5fc838f60279dfe7bff590283b7a6a0027f
Next task is being able to specify a value in the remove/removeSync call so you can delete dupsort values (I'll ref this ticket with future commit(s)).

**Comment by kylebernhardy** [comment]
Thank you so much!  You have no idea how much this will improve our product.

**Comment by kriszyp** [comment]
I have added better support for dupSort databases with the v0.9.4 release, which includes:
* remove/removeSync now support specifying a value as the second argument for deleting individual entries that may sure a duplicate key
* getValues(key) was added to iterate over all values of a given key
* getKeys(rangeOptions) was added to easily iterate over all keys in a range, without returning duplicate keys

Let me know if you find any issues with this, or if there is anything else that would be useful for dupSort dbs.

**Comment by kylebernhardy** [comment]
This looks great!  I have not found any issues.

Thanks for adding dup sorted keys!

**Comment by kylebernhardy** [comment]
Does the transaction function execute it's transactional block in the interval worker queue like put/remove? Is that what would occur if the transaction function is async? Is there a way to rollback / abort the entire transaction if a part of the block fails?

**Comment by kriszyp** [comment]
No, it does not. And while you can return a promise from the transaction block/callback so that _your_ code is async, once the promise resolves, the transaction would still be committed synchronously in the main thread. You can abort a transaction by throwing an error in the transaction callback (or rejecting the returned promise).

The queued worker thread execution works by running the entire transaction in a worker thread (in C++ code), which is not allowed to execute any JS (due to V8 threading constraints), so there isn't really any way to have such transactions determine whether to abort or commit based on a runtime JS condition. However, this is exactly why lmdb-store uses the entire conditional version-based put/remove system (using ifVersion()), since this allows for conditional writes to be communicated to the worker thread that does the writes/commits. The conditional version-based writes are also composable, you can actually nest ifVersion() blocks inside of each other as well, if that helps.

If you are trying to translate something more akin to SQL-style transactions, where a transaction can be kept open arbitrarily long with any arbitrary decisions being made about whether to abort or commit during the transaction. And yeah, you can do this with standard main thread transactions (losing the advantage of worker threads). It might also be possible to do a "pseudo" transaction, where you run some DSL/script of commands that interacts with the DB and for each read, it records the expected version that was used to inform the script and then submits all the accumulated writes along with the conditional versions of all the expected versions from the pseudo-transaction to achieve true transaction atomicity (and retrying if any version number changes).

**Comment by kylebernhardy** [comment]
Thanks again for the detailed information.  I think nesting ifNotExists/ifVersion provides what we would need for our CUD operations. LMDB is so fast as it is that the main process bound writes have worked for us well, but with the work you have done in lmdb-store I can see our write operations far outpacing our current benchmarks.  Even if the worker thread batching doesn't accommodate our needs you have given us the access to the underlying library for us to run our existing code as is. 

Thank you again.

**Comment by kriszyp** [comment]
If you have other ideas for how to enqueue conditional writes, let me know.

BTW, are you using `noSync` (or `noMetaSync`) for your databases? Sync'ing has generally been the biggest source of performance degradation for me, but we have had issues with not sync'ing making databases prone to data loss or corruption in the event of power loss or crash.

**Comment by kylebernhardy** [comment]
I have seen the same thing with noSync & performance.  We were considering making it a config option, but with lmdb-store I'm hoping we can bypass that and have enhanced write perfromance with durability guarantees.  I got pulled away on a few issues but will be able to pivot back to PoC-ing writes as we discussed above.  

Have ever considered adding TTL to this or maybe another library?

**Comment by kriszyp** [comment]
TTL, as in time-to-live? Like an expiration time on entries so they are periodically pruned/removed? It seems like that would be a higher level concern than lmdb-store, but I may be misunderstanding.

**Comment by kylebernhardy** [comment]
Sorry, I did mean time-to-live :). Agree on the higher order implementation.  We have already built it in, but was curious regarding if you had considered it, again not a necessity on our end.

**Comment by kylebernhardy** [comment]
In the readme it sounds like lmdb-store is using LMDB v1.0 (https://github.com/DoctorEvidence/lmdb-store#upgrade-note).  

When I inspect the version attribute:
`require('lmdb-store').version`
returns:
`{
  "versionString": "LMDB 0.9.90: (May 1, 2017)",
  "major": 0,
  "minor": 9,
  "patch": 90
}`

Just curious if this is an anomaly in my project or is expected.

**Comment by kriszyp** [comment]
My understanding of the LMDB version/format comes entirely from https://twitter.com/hyc_symas/status/1315445394034302977 (and lmdb-store is using the latest from the mdb.master3 branch mentioned in that tweet).
Maybe 0.9.90 is the numerical representation for "1.0RC"? (I can update the docs to make that clear).

**Comment by kylebernhardy** [comment]
Ok, I just wanted to make sure I didn't have a weird dependency issue happening (not sure how that theoretically would happen). Thank you again!
