### ISSUE TITLE
Maybe use cursor stats for getValuesCount without a range?

### ISSUE THREAD

**Issue by vladar** [DoctorEvidence/lmdb-store#66]
Looks like when using `dupSort` LMDB creates another tree under the hood and then you can get a count of all values without iterating:

http://www.lmdb.tech/doc/group__mdb.html#ga4041fd1e1862c6b7d5f10590b86ffbe2

Is it possible to access those stats for fast counts?

**Comment by kriszyp** [comment]
Nice, I hadn't noticed that before, that would be good to use.

**Comment by kriszyp** [comment]
This should be available in the beta release of v1.6 (1.6.0-beta.1) if you want to give it a try (along with a _lot_ of other performance optimizations/upgrades)

**Comment by vladar** [comment]
Awesome, I wanted to try it but quickly realized that one method is missing for fast counts by range with `dupSort` (e.g. `getRangeValuesCount` for the lack of a better name).

Let me explain. Usually what you have with `dupSort` db is something like this:

```
* value1
    - id1
    - id2
    - id3
* value2
    - id4
    - id5
 ```

So if you have a range query (with `in`, `>` or `>=`) you still have to traverse all matching keys, call `getValuesCount()` for each key and sum the results. It should be fast but really depends on how unique your values are. In the worst case you may be scanning through all keys again.

This is inevitable but if it happens on the js side of things - it will probably lose all the benefits of fast `getKeysCount`?

**Comment by kriszyp** [comment]
I think this should simply be the result `getCount({start: 'value1',end: 'value3'})`, which you should be able to call for dupSort store, and which should count all values/entries, without any JS side execution. However, you are right that this function isn't fully optimized to use mdb_cursor_count. Instead of only using mdb_cursor_count for getValuesCount, I will change the code so we use mdb_cursor_count anytime we are counting entries in a dupSort table (and start and end aren't specified).
